# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
target 'WebRTCapp' do
  platform :ios, '10.0'
  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCapp
  pod 'GoogleWebRTC'
  pod 'Starscream', '~> 4.0.0'
  pod 'SwiftWebSocket'
  
  #target 'WebRTCappTests' do
  # inherit! :search_paths
    # Pods for testing
    #end

end
